default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: realsecond_development
  user: postgres
  password: postgres


test:
  <<: *default
  database: realsecond_test
  user: postgres
  password: postgres


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
